# Generated by Django 3.1.5 on 2021-01-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='No tag', max_length=150),
        ),
    ]
