# Generated by Django 3.1.5 on 2021-01-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_category_link'),
    ]

    operations = [
    ]
