# Generated by Django 3.1.5 on 2021-01-29 11:59

from django.db import migrations


def link_category(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    Category = apps.get_model('blog', 'Category')
    for post in BlogPost.objects.all():
        if post.category is not None:
            desig, created = Category.objects.get_or_create(name=post.category)
            post.category_link = desig
            post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogpost_category_link'),
    ]

    operations = [
        migrations.RunPython(link_category)
    ]
