# Generated by Django 3.1.5 on 2021-01-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_blogpost_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='category_link',
            new_name='category',
        ),
    ]
