# Generated by Django 3.1.5 on 2021-02-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentToComment',
        ),
    ]
