# Generated by Django 3.1.5 on 2021-02-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_delete_commenttocomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
