# Generated by Django 3.1.5 on 2021-02-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='reply',
        ),
    ]
