# Generated by Django 3.1.5 on 2021-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210212_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='users_follow', to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='users_subs', to='blog.UserProfile'),
        ),
    ]
